Repository kube-logging/logging-operator, pull requests merged in 2019-11, with the labels that each got.

#202 Documentation Refactor
  README.md
  docs/deploy/README.md
  docs/example-es-nginx.md
  docs/example-es.md
  docs/example-kafka-nginx.md
  docs/example-loki-nginx.md
  docs/example-s3.md
Labels: documentation

#203 Fluent container version upgrade
  README.md
  api/v1beta1/logging_types.go
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  docs/crds.md
Labels: enhancement

#204 Fluentd output tests
  pkg/model/output/azurestore_test.go
  pkg/model/output/elasticsearch_test.go
  pkg/model/output/gcs_test.go
  pkg/model/output/kafka_test.go
  pkg/model/output/oss_test.go
  pkg/model/output/s3_test.go
  pkg/model/output/sumologic_test.go
Labels: testing

#196 Security context Support
  api/v1beta1/common_types.go
  api/v1beta1/logging_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/security/README.md
  pkg/resources/fluentbit/daemonset.go
  pkg/resources/fluentd/statefulset.go
  pkg/util/util.go
Labels: community, feature-request, security

#206 Fluentbit advanced config support
  api/v1beta1/fluentbit_types.go
  api/v1beta1/logging_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/fluentbit.md
  docs/img/fluentbit.png
  go.mod
  pkg/resources/fluentbit/config.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentbit/daemonset.go
  pkg/resources/fluentbit/psp.go
Labels: enhancement, filter

#207 Fluentd concat filter plugin support
  api/v1beta1/flow_types.go
  api/v1beta1/logging_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  charts/logging-operator/templates/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/templates/logging.banzaicloud.io_flows.yaml
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_flows.yaml
  docs/crds.md
  docs/plugins/Readme.md
  docs/plugins/filters/concat.md
  pkg/model/filter/concat.go
  pkg/model/filter/zz_generated.deepcopy.go
Labels: community, enhancement, filter

#209 custom fluent-bit config
  api/v1beta1/fluentbit_types.go
  charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/crds.md
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentbit/daemonset.go
Labels: enhancement

#208 manual scaling for fluentd
  api/v1beta1/common_types.go
  api/v1beta1/fluentd_types.go
  api/v1beta1/logging_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  go.mod
  go.sum
  pkg/resources/fluentd/statefulset.go
Labels: enhancement

#210 Crd docs update
  docs/crds.md
  docs/img/logging-operator-v2-architecture.png
  docs/logging-operator-monitoring.md
  docs/security/README.md
Labels: documentation

#222 fix reference issues
  pkg/sdk/model/output/buffer.go
  pkg/sdk/model/output/format.go
Labels: bug

#223 Kinesis output support
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  docs/crds.md
  pkg/sdk/api/v1beta1/logging_types.go
Labels: fluentd, output

#220 Kinesis Stream support
  docs/plugins/Readme.md
  docs/plugins/outputs/kinesis_stream.md
  pkg/sdk/model/output/kinesis_stream.go
  pkg/sdk/model/output/kinesis_stream_test.go
  pkg/sdk/model/output/zz_generated.deepcopy.go
Labels: community, enhancement, fluentd, output

#226 Kinesis refactor
  Makefile
  charts/logging-operator/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/templates/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/examples/logging_output_kinesis.yaml
  docs/plugins/outputs/kinesis_stream.md
  pkg/sdk/api/v1beta1/output_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/model/output/kinesis_stream.go
Labels: bug, fluentd

#234 Fluentbit input tailers, error handling improvements
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/samples/logging_v1alpha2_logging_debug.yaml
  config/samples/logging_v1alpha2_logging_tailer.yaml
  controllers/logging_controller.go
  docs/crds.md
  main.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentbit/daemonset.go
  pkg/resources/fluentbit/fluentbit.go
  pkg/resources/fluentbit/psp.go
  pkg/resources/fluentbit/rbac.go
  pkg/resources/fluentbit/service.go
  pkg/resources/fluentd/appconfigmap.go
  pkg/resources/fluentd/config.go
  pkg/resources/fluentd/configsecret.go
  pkg/resources/fluentd/fluentd.go
  pkg/resources/fluentd/outputsecret.go
  pkg/resources/fluentd/psp.go
  pkg/resources/fluentd/rbac.go
  pkg/resources/fluentd/service.go
  pkg/resources/fluentd/statefulset.go
  pkg/resources/reconciler.go
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/fluentd_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/util/util.go
Labels: refactor

#235 Exception detector plugin
  .idea/copyright/Banzai_Cloud.xml
  README.md
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_flows.yaml
  docs/crds.md
  docs/plugins/Readme.md
  docs/plugins/filters/detect_exceptions.md
  pkg/sdk/api/v1beta1/flow_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/model/filter/detect_exceptions.go
  pkg/sdk/model/filter/detect_exceptions_test.go
  pkg/sdk/model/filter/zz_generated.deepcopy.go
Labels: fluentd, output

#246 Fix parser id, to avoid duplicates. Deprecate multiple parsers in favour of a single parser.
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_flows.yaml
  docs/plugins/filters/parser.md
  pkg/k8sutil/resource.go
  pkg/resources/model/system.go
  pkg/sdk/model/filter/parser.go
  pkg/sdk/model/filter/zz_generated.deepcopy.go
  pkg/sdk/plugins/plugin.go
Labels: fluentd, refactor

#251 Fix parser
  pkg/resources/model/system.go
Labels: refactor

#250 fix label handling
  Makefile
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/samples/logging_v1alpha2_logging_labels.yaml
  docs/crds.md
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentbit/daemonset.go
  pkg/resources/fluentbit/fluentbit.go
  pkg/resources/fluentbit/meta.go
  pkg/resources/fluentbit/psp.go
  pkg/resources/fluentbit/rbac.go
  pkg/resources/fluentbit/service.go
  pkg/resources/fluentd/appconfigmap.go
  pkg/resources/fluentd/configsecret.go
  pkg/resources/fluentd/fluentd.go
  pkg/resources/fluentd/meta.go
  pkg/resources/fluentd/psp.go
  pkg/resources/fluentd/rbac.go
  pkg/resources/fluentd/service.go
  pkg/resources/fluentd/statefulset.go
  pkg/resources/templates/templates.go
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/fluentd_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
Labels: core, refactor

#253 Add support for Priority Classes for fluentd and fluentbit
  charts/logging-operator-logging/README.md
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/crds.md
  go.mod
  go.sum
  pkg/resources/fluentbit/daemonset.go
  pkg/resources/fluentd/statefulset.go
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/fluentd_types.go
Labels: community, core

#260 Fixes for ServiceOperator-less prometheus monitoring
  pkg/resources/fluentbit/service.go
  pkg/resources/fluentd/service.go
  pkg/sdk/api/v1beta1/logging_types.go
Labels: bug, core

#262 Expose `EnableRecreateWorkloadOnImmutableFieldChange` in helm chart
  charts/logging-operator-logging/README.md
  charts/logging-operator-logging/templates/logging.yaml
  charts/logging-operator-logging/values.yaml
Labels: community

#270 Fluent output to file and configure sane logrotate
  charts/logging-operator/templates/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/samples/logging_v1alpha2_logging_disablelogrotate.yaml
  docs/crds.md
  pkg/resources/fluentd/statefulset.go
  pkg/sdk/api/v1beta1/fluentd_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/go.mod
  pkg/sdk/go.sum
Labels: core, fluentd, improvement

#274 Allow annotations in logging-operator helm chart
  charts/logging-operator/README.md
  charts/logging-operator/templates/deployment.yaml
Labels: chart, community, contribution, improvement

#273 Assume Role Support
  charts/logging-operator/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/templates/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/plugins/outputs/cloudwatch.md
  pkg/sdk/model/output/cloudwatch.go
Labels: enhancement, fluentd, output
