Repository kube-logging/logging-operator, pull requests merged in 2020-06, with the labels that each got.

#501 Kafka | Add CA certs from system option
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/plugins/outputs/kafka.md
  pkg/sdk/model/output/kafka.go
  pkg/sdk/model/output/zz_generated.deepcopy.go
  pkg/sdk/static/gen/crds/generated.go
Labels: community, contribution, fluentd

#503 ltsv parser parameter support
  charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_flows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_flows.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/plugins/filters/parser.md
  pkg/sdk/model/filter/parser.go
  pkg/sdk/static/gen/crds/generated.go
Labels: parser

#504 Add Worker support to fluentd spec
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  pkg/resources/fluentd/config.go
  pkg/resources/fluentd/configsecret.go
  pkg/sdk/api/v1beta1/fluentd_types.go
  pkg/sdk/static/gen/crds/generated.go
Labels: community, core
