Repository kube-logging/logging-operator, pull requests merged in 2020-04, with the labels that each got.

#347 allow adding AWS instance metadata on fluentbit records
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/samples/logging_v1alpha2_logging_debug.yaml
  docs/crds/v1beta1/fluentbit_types.md
  pkg/resources/fluentbit/config.go
  pkg/resources/fluentbit/configsecret.go
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/static/gen/crds/generated.go
Labels: community, contribution

#434 Documentation refactor
  README.md
  cmd/docs.go
  docs/_index.md
  docs/crds/_index.md
  docs/crds/v1beta1/_index.md
  docs/crds/v1beta1/clusterflow_types.md
  docs/crds/v1beta1/clusteroutput_types.md
  docs/crds/v1beta1/common_types.md
  docs/crds/v1beta1/flow_types.md
  docs/crds/v1beta1/fluentbit_types.md
  docs/crds/v1beta1/fluentd_types.md
  docs/crds/v1beta1/groupversion_info.md
  docs/crds/v1beta1/logging_types.md
  docs/crds/v1beta1/output_types.md
  docs/security/_index.md
  pkg/sdk/api/v1beta1/clusterflow_types.go
  pkg/sdk/api/v1beta1/clusteroutput_types.go
  pkg/sdk/api/v1beta1/common_types.go
  pkg/sdk/api/v1beta1/flow_types.go
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/fluentd_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/output_types.go
Labels: documentation

#432 FluentBit Default Liveness support
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/crds/v1beta1/fluentbit_types.md
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/static/gen/crds/generated.go
Labels: core, fluentbit

#435 Fluentd plugin version docs update
  docs/plugins/_index.md
  pkg/sdk/model/output/elasticsearch.go
  pkg/sdk/model/output/kafka.go
  pkg/sdk/model/output/kinesis_stream.go
  pkg/sdk/model/output/loki.go
  pkg/sdk/model/output/newrelic.go
  pkg/sdk/model/output/sumologic.go
Labels: documentation

#436 Release 3.1.0-rc1 helm chart support
  charts/logging-demo/Chart.yaml
  charts/logging-operator-logging/Chart.yaml
  charts/logging-operator/Chart.yaml
  charts/logging-operator/README.md
  charts/logging-operator/values.yaml
Labels: chart

#442 fix field name in docs example
  docs/plugins/filters/parser.md
Labels: contribution, documentation

#447 Fix/docs parse
  docs/plugins/_index.md
  docs/plugins/filters/parser.md
  pkg/sdk/model/filter/parser.go
  pkg/sdk/model/output/elasticsearch.go
  pkg/sdk/model/output/kafka.go
  pkg/sdk/model/output/kinesis_stream.go
Labels: documentation

#450 Broken url fix
  docs/plugins/outputs/logz.md
  docs/plugins/outputs/newrelic.md
  pkg/sdk/model/output/logz.go
  pkg/sdk/model/output/newrelic.go
Labels: documentation

#453 ReGenerate docs
  docs/crds/v1beta1/logging_types.md
  docs/plugins/filters/grep.md
  docs/plugins/filters/parser.md
  docs/plugins/filters/prometheus.md
  docs/plugins/outputs/elasticsearch.md
  docs/plugins/outputs/forward.md
Labels: bug, documentation

#452 FluentD default liveness check script parameter fix
  fluentd-image/v1.7/healthy.sh
  fluentd-image/v1.9/healthy.sh
Labels: bug, core, fluentd
