Repository kube-logging/logging-operator, pull requests merged in 2020-08, with the labels that each got.

#538 Logging-demo chart dependency update minio 3.0.7 -> 5.0.33
  charts/logging-demo/charts/minio-3.0.7.tgz
  charts/logging-demo/charts/minio-5.0.33.tgz
  charts/logging-demo/requirements.lock
  charts/logging-demo/requirements.yaml
  charts/logging-demo/values.yaml
Labels: chart

#536 AWS ELasticSearch Output support
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/crds/v1beta1/output_types.md
  docs/plugins/_index.md
  docs/plugins/outputs/aws_elasticsearch.md
  fluentd-image/v1.10/Dockerfile
  fluentd-image/v1.11/Dockerfile
  fluentd-image/v1.7/Dockerfile
  fluentd-image/v1.9/Dockerfile
  pkg/sdk/api/v1beta1/output_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/model/output/aws_elasticsearch.go
  pkg/sdk/model/output/aws_elasticsearch_test.go
  pkg/sdk/model/output/zz_generated.deepcopy.go
  pkg/sdk/static/gen/crds/generated.go
Labels: core, enhancement, output

#537 Stricter RBAC Rules
  Makefile
  charts/logging-operator/templates/clusterrole.yaml
  charts/logging-operator/templates/clusterrolebinding.yaml
  charts/logging-operator/templates/rbac.yaml
  charts/logging-operator/templates/serviceaccount.yaml
  docs/deploy/manifests/rbac.yaml
  docs/security/manifests/rbac.yaml
Labels: core, security

#539 fix: logging-operator-logging logging.yaml template
  charts/logging-operator-logging/Chart.yaml
  charts/logging-operator-logging/templates/logging.yaml
Labels: bug, chart

#542 Chart TLS Setting refactor
  charts/logging-demo/templates/logging.yaml
  charts/logging-operator-logging/templates/logging.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/crds/v1beta1/fluentbit_types.md
  docs/crds/v1beta1/fluentd_types.md
  pkg/sdk/api/v1beta1/fluentbit_types.go
  pkg/sdk/api/v1beta1/fluentd_types.go
  pkg/sdk/static/gen/crds/generated.go
Labels: chart, core

#541 New Fluentbit version 1.5.0 -> 1.5.2
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  config/samples/logging_v1alpha2_logging_debug.yaml
  pkg/sdk/api/v1beta1/logging_types.go
Labels: fluentbit

#543 Fluentd 1.11.1
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  docs/crds/_index.md
  docs/plugins/_index.md
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/model/filter/prometheus.go
  pkg/sdk/model/output/aws_elasticsearch.go
  pkg/sdk/model/output/cloudwatch.go
  pkg/sdk/model/output/datadog.go
  pkg/sdk/model/output/elasticsearch.go
  pkg/sdk/model/output/kafka.go
  pkg/sdk/model/output/kinesis_firehose.go
  pkg/sdk/model/output/kinesis_stream.go
  pkg/sdk/model/output/loki.go
  pkg/sdk/model/output/s3.go
  pkg/sdk/model/output/splunk_hec.go
Labels: fluentd

#545 docs: fix hugo compatibility
  pkg/sdk/model/output/logdna.go
Labels: documentation

#548 Downgrade Prometheus gem 2.1.0 -> 0.9.0
  fluentd-image/v1.11/Dockerfile
Labels: bug

#549 Redis Output Plugin Support
  .circleci/config.yml
  charts/logging-operator-logging/README.md
  charts/logging-operator/README.md
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/crds/_index.md
  docs/crds/v1beta1/output_types.md
  docs/plugins/_index.md
  docs/plugins/outputs/redis.md
  fluentd-image/v1.10/Dockerfile
  fluentd-image/v1.11/Dockerfile
  fluentd-image/v1.7/Dockerfile
  fluentd-image/v1.9/Dockerfile
  pkg/sdk/api/v1beta1/logging_types.go
  pkg/sdk/api/v1beta1/output_types.go
  pkg/sdk/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/model/output/redis.go
  pkg/sdk/model/output/redis_test.go
  pkg/sdk/model/output/zz_generated.deepcopy.go
  pkg/sdk/static/gen/crds/generated.go
Labels: fluentd, output

#558 AWS Process Credentials Support
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/plugins/outputs/kinesis_firehose.md
  docs/plugins/outputs/kinesis_stream.md
  pkg/sdk/model/output/kinesis_firehose.go
  pkg/sdk/model/output/kinesis_stream.go
  pkg/sdk/model/output/kinesis_stream_test.go
  pkg/sdk/model/output/zz_generated.deepcopy.go
  pkg/sdk/static/gen/crds/generated.go
Labels: core

#563 Splunk doc
  docs/img/splunk.png
  docs/img/splunk_dash.png
  docs/quickstarts/splunk.md
Labels: documentation

#564 Splunk parameter fix
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/plugins/outputs/splunk_hec.md
  pkg/sdk/model/output/splunk_hec.go
  pkg/sdk/model/output/splunk_hec_test.go
  pkg/sdk/static/gen/crds/generated.go
Labels: bug
