Repository kube-logging/logging-operator, pull requests merged in 2024-11, with the labels that each got.

#1839 docs: add nullout
  charts/logging-operator/charts/crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  cmd/docs.go
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/_index.md
  docs/configuration/plugins/outputs/null.md
  pkg/sdk/logging/api/v1alpha1/zz_generated.deepcopy.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/logging/model/output/null.go
  pkg/sdk/logging/model/output/null_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: enhancement, documentation, output, fluentd, go

#1838 feat(e2e): add metrics e2e-test
  e2e/go.mod
  e2e/go.sum
  e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
  pkg/resources/fluentbit/prometheusrules.go
  pkg/resources/fluentbit/service.go
  pkg/resources/nodeagent/service.go
Labels: enhancement, testing, go

#1828 OpenSearch remove_keys parameter support
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/outputs/opensearch.md
  pkg/sdk/logging/model/output/opensearch.go
Labels: enhancement

#1854 fix: image signing
  .github/workflows/artifacts.yaml
Labels: bugfix

#1858 chore: use consts instead of literals
  .gitignore
  pkg/resources/fluentbit/service.go
  pkg/resources/fluentd/service.go
  pkg/resources/nodeagent/service.go
  pkg/resources/syslogng/service.go
Labels: refactor

#1857 Telemetry Controller compatibility example
  config/samples/multitenant-routing-tc/tc-simple/README.md
  config/samples/multitenant-routing-tc/tc-simple/collector.yaml
  config/samples/multitenant-routing-tc/tc-simple/tenant-a.yaml
  config/samples/multitenant-routing-tc/tc-simple/tenant-b.yaml
  config/samples/multitenant-routing-tc/tc-simple/tenant-infra.yaml
  config/samples/multitenant-routing/logging/tenant-infra-logging.yaml
Labels: documentation

#1860 fix: prometheus rule overrides swaps whole list
  pkg/resources/fluentbit/prometheusrules.go
  pkg/resources/fluentd/prometheusrules.go
  pkg/resources/syslogng/prometheusrules.go
  pkg/sdk/logging/api/v1beta1/common_types.go
  pkg/sdk/logging/api/v1beta1/commont_types_test.go
Labels: bugfix

#1861 feat(gha): provide crds subchart as oci artifact
  .github/workflows/artifacts.yaml
  Makefile
  charts/logging-operator/Chart.yaml
  charts/logging-operator/README.md
  charts/logging-operator/charts/logging-operator-crds/Chart.yaml
  charts/logging-operator/charts/logging-operator-crds/README.md
  charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_eventtailers.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_hosttailers.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_flows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggingroutes.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_nodeagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusterflows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngconfigs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngflows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/values.yaml
  charts/logging-operator/values.yaml
Labels: feature

#1865 chore(deps): bump deps
  .github/archive/trigger-submodule-update.yaml
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
  .github/workflows/e2e.yaml
Labels: dependencies

#1863 fix: long generated names
  e2e/go.mod
  e2e/go.sum
  pkg/resources/kubetool/utils.go
  pkg/resources/kubetool/utils_test.go
  pkg/resources/nodeagent/nodeagent.go
  pkg/sdk/go.mod
  pkg/sdk/go.sum
  pkg/sdk/logging/api/v1beta1/common_types_test.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/model/syslogng/config/go.mod
  pkg/sdk/logging/model/syslogng/config/go.sum
Labels: bugfix

#1867 fix: nil ptr panic on empty secrets slice during cfg-check
  pkg/resources/fluentd/outputsecret.go
Labels: bugfix

#1868 fix: make workload meta overrides not required
  charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_hosttailers.yaml
  charts/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml
  config/crd/bases/logging-extensions.banzaicloud.io_hosttailers.yaml
  pkg/sdk/extensions/api/v1alpha1/eventtailer_types.go
  pkg/sdk/extensions/api/v1alpha1/hosttailer_types.go
Labels: bugfix

#1871 feat: add syslogng flow-output validation
  pkg/sdk/logging/model/syslogng/config/config.go
  pkg/sdk/logging/model/syslogng/config/flow.go
Labels: enhancement
