Repository kube-logging/logging-operator, pull requests merged in 2024-04, with the labels that each got.

#1715 add missing dnsconfig to configcheck pods as well
  pkg/resources/fluentd/appconfigmap.go
Labels: bugfix

#1729 chore(fluentd): do not override fluentd's default buffer size
  docs/configuration/plugins/outputs/buffer.md
  pkg/sdk/logging/model/output/aws_elasticsearch_test.go
  pkg/sdk/logging/model/output/azurestore_test.go
  pkg/sdk/logging/model/output/buffer.go
  pkg/sdk/logging/model/output/cloudwatch_test.go
  pkg/sdk/logging/model/output/datadog_test.go
  pkg/sdk/logging/model/output/elasticsearch_test.go
  pkg/sdk/logging/model/output/file_test.go
  pkg/sdk/logging/model/output/format_test.go
  pkg/sdk/logging/model/output/gcs_test.go
  pkg/sdk/logging/model/output/http_test.go
  pkg/sdk/logging/model/output/kafka_test.go
  pkg/sdk/logging/model/output/kinesis_firehose_test.go
  pkg/sdk/logging/model/output/kinesis_stream_test.go
  pkg/sdk/logging/model/output/logdna_test.go
  pkg/sdk/logging/model/output/loki_test.go
  pkg/sdk/logging/model/output/newrelic_test.go
  pkg/sdk/logging/model/output/opensearch_test.go
  pkg/sdk/logging/model/output/oss_test.go
  pkg/sdk/logging/model/output/redis_test.go
  pkg/sdk/logging/model/output/s3_test.go
  pkg/sdk/logging/model/output/splunk_hec_test.go
  pkg/sdk/logging/model/output/sqs_test.go
  pkg/sdk/logging/model/output/sumologic_test.go
  pkg/sdk/logging/model/output/syslog_test.go
  pkg/sdk/logging/model/output/vmware_log_intelligence_test.go
  pkg/sdk/logging/model/output/vmware_loginsight_test.go
  pkg/sdk/logging/model/render/fluent_test.go
Labels: breaking-change

#1730 feat: protected clusteroutput for fluentd
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  controllers/logging/logging_controller_test.go
  docs/configuration/crds/v1beta1/clusteroutput_types.md
  pkg/resources/model/reconciler.go
  pkg/resources/model/system.go
  pkg/sdk/logging/api/v1beta1/clusteroutput_types.go
Labels: enhancement

#1720 fix: Add Buffer to Gelf Outputs
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/outputs/gelf.md
  pkg/sdk/logging/model/output/gelf.go
  pkg/sdk/logging/model/output/gelf_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: enhancement
