Repository kube-logging/logging-operator, pull requests merged in 2024-01, with the labels that each got.

#1617 Enable using custom PVC without a template for the statefulset (for the buffer volume and also as extravolumes)
  config/samples/pvc-notemplate.yaml
  go.work.sum
  pkg/resources/fluentd/statefulset.go
Labels: enhancement

#1640 Fix loggingroute notifications for changes in the logging resource status
  controllers/logging/loggingroute_controller.go
  pkg/resources/fluentbit/tenants.go
Labels: bugfix

#1641 config type move
  docs/configuration/crds/v1beta1/_index.md
  docs/configuration/crds/v1beta1/fluentd_config_types.md
  docs/configuration/crds/v1beta1/fluentd_types.md
  docs/configuration/crds/v1beta1/syslogng_config_types.md
  docs/configuration/crds/v1beta1/syslogng_types.md
  go.work.sum
  pkg/sdk/logging/api/v1beta1/fluentd_config_types.go
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
  pkg/sdk/logging/api/v1beta1/syslogng_config_types.go
  pkg/sdk/logging/api/v1beta1/syslogng_types.go
Labels: documentation

#1644 fix: add namespace filter when listing aggregator configs
  pkg/resources/model/repository.go
Labels: bugfix

#1643 fix(syslog-ng): add port to OpenObserve output
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
  docs/configuration/plugins/_index.md
  docs/configuration/plugins/syslogng-outputs/openobserve.md
  go.work.sum
  pkg/sdk/logging/model/syslogng/config/output_tests/openobserve_test.go
  pkg/sdk/logging/model/syslogng/output/openobserve.go
Labels: bugfix

#1646 fix: add namespace filter when listing aggregator configs (#1644)
  pkg/resources/model/repository.go
Labels: bugfix
