Repository kube-logging/logging-operator, pull requests merged in 2024-12, with the labels that each got.

#1870 feat: support enable ipv6
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
  config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/configuration/crds/v1beta1/fluentbit_types.md
  docs/configuration/crds/v1beta1/fluentd_types.md
  pkg/resources/fluentbit/config.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentd/config.go
  pkg/resources/fluentd/configsecret.go
  pkg/sdk/logging/api/v1beta1/fluentbit_types.go
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
Labels: enhancement

#1873 feat: add option to cleanup stuck finalizers
  Makefile
  charts/logging-operator/README.md
  charts/logging-operator/templates/clusterrole.yaml
  charts/logging-operator/templates/clusterrolebinding.yaml
  charts/logging-operator/templates/serviceaccount.yaml
  charts/logging-operator/values.yaml
  controllers/logging/logging_controller.go
  main.go
Labels: feature

#1866 breaking: remove sumologic filter and output, enchance_k8s filter
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_flows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_flows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_flows.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/crds/v1beta1/flow_types.md
  docs/configuration/crds/v1beta1/output_types.md
  docs/configuration/plugins/_index.md
  e2e/common/helpers.go
  e2e/fluentd-aggregator-namespacelabel/fluentd_aggregator_test.go
  e2e/fluentd-aggregator/fluentd_aggregator_test.go
  e2e/volumedrain/volumedrain_test.go
  pkg/resources/fluentd/rbac.go
  pkg/resources/syslogng/rbac.go
  pkg/sdk/logging/api/v1alpha1/output_types.go
  pkg/sdk/logging/api/v1alpha1/zz_generated.deepcopy.go
  pkg/sdk/logging/api/v1beta1/flow_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/api/v1beta1/output_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/logging/model/filter/enhance_k8s.go
  pkg/sdk/logging/model/filter/enhance_k8s_test.go
  pkg/sdk/logging/model/filter/sumologic.go
  pkg/sdk/logging/model/filter/sumologic_test.go
  pkg/sdk/logging/model/filter/zz_generated.deepcopy.go
  pkg/sdk/logging/model/output/sumologic.go
  pkg/sdk/logging/model/output/sumologic_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: breaking-change

#1881 feat: make fluentbit pause on chunks overlimit configurable
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_nodeagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
  config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
  docs/configuration/crds/v1beta1/fluentbit_types.md
  pkg/resources/fluentbit/tenants.go
  pkg/resources/nodeagent/nodeagent.go
  pkg/sdk/logging/api/v1beta1/fluentbit_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: enhancement

#1875 feat: support rdkafka2 options
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/outputs/kafka.md
  pkg/sdk/logging/model/output/kafka.go
  pkg/sdk/logging/model/output/kafka_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: enhancement

#1876 feat: add TC migration option
  .github/workflows/artifacts.yaml
  .gitignore
  charts/logging-operator/Chart.lock
  charts/logging-operator/Chart.yaml
  charts/logging-operator/README.md
  charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_eventtailers.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging-extensions.banzaicloud.io_eventtailers.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/templates/clusterrole.yaml
  charts/logging-operator/values.yaml
  config/crd/bases/logging-extensions.banzaicloud.io_eventtailers.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/rbac/role.yaml
  config/samples/telemetry-controller-routing/README.md
  config/samples/telemetry-controller-routing/tc-tenant-a-logging.yaml
  config/samples/telemetry-controller-routing/tc-tenant-b-logging.yaml
  config/samples/telemetry-controller-routing/tc-tenant-infra-logging.yaml
  config/samples/telemetry-controller-routing/tc-tenant-infra-receiver.yaml
  controllers/logging/telemetry_controller_controller.go
  docs/configuration/crds/v1beta1/logging_types.md
  go.mod
  go.sum
  go.work
  hack/test.sh
  main.go
  pkg/resources/fluentbit/tenants.go
  pkg/resources/telemetry-controller/resources.go
  pkg/sdk/extensions/api/v1alpha1/eventtailer_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
Labels: feature

#1883 feat: upgrade renovate config
  Makefile
  renovate.json
Labels: dependencies

#1884 fix: mk deps
  Makefile
Labels: dependencies

#1891 fix: fluentd prom metrics invalid addr
  pkg/resources/fluentbit/config.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentd/config.go
  pkg/resources/fluentd/configsecret.go
Labels: bugfix

#1895 chore: remove dependabot
  .github/dependabot.yaml
  renovate.json
Labels: dependencies
