Repository kube-logging/logging-operator, pull requests merged in 2024-02, with the labels that each got.

#1602 Feat: add PodDisruptionBudget for fluentd
  .gitignore
  charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/templates/clusterrole.yaml
  config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/rbac/role.yaml
  controllers/logging/logging_controller.go
  docs/configuration/crds/v1beta1/fluentd_types.md
  pkg/resources/fluentd/fluentd.go
  pkg/resources/fluentd/pdb.go
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
Labels: enhancement

#1678 feat(fluentbit): add storage.delete_irrecoverable_chunks option
  charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
  config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
  docs/configuration/crds/v1beta1/fluentbit_types.md
  pkg/sdk/logging/api/v1beta1/fluentbit_types.go
Labels: enhancement

#1672 Fix fluentdconfig and syslogngconfig deletion
  charts/logging-operator/templates/clusterrole.yaml
  config/rbac/role.yaml
  config/samples/fluentdconfig.yaml
  controllers/logging/logging_controller.go
  controllers/logging/logging_controller_test.go
  main.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentbit/tenants.go
  pkg/resources/fluentd/dataprovider.go
  pkg/resources/fluentd/fluentd.go
  pkg/resources/fluentd/meta.go
  pkg/resources/model/reconciler.go
  pkg/resources/model/resources.go
  pkg/resources/model/system.go
  pkg/resources/syslogng/dataprovider.go
  pkg/resources/syslogng/meta.go
  pkg/resources/syslogng/statefulset.go
  pkg/resources/syslogng/syslogng.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: bugfix

#1680 fix: remove requeue after
  pkg/resources/fluentd/fluentd.go
  pkg/resources/syslogng/syslogng.go
Labels: bugfix

#1679 fix: pass complete security context to pods
  pkg/resources/fluentd/appconfigmap.go
  pkg/resources/fluentd/drainjob.go
  pkg/resources/fluentd/statefulset.go
Labels: enhancement

#1631 Logo update and docs cleanup
  README.md
  docs/README.md
  docs/Readme.md
  docs/examples/logging_logging_default_route.yaml
  docs/img/lo.svg
Labels: documentation
