Repository kube-logging/logging-operator, pull requests merged in 2025-03, with the labels that each got.

#1959 feat: add varlibcontainers volume as optional
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/configuration/crds/v1beta1/fluentbit_types.md
  pkg/resources/fluentbit/daemonset.go
  pkg/sdk/logging/api/v1beta1/fluentbit_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
Labels: enhancement

#1969 fix(ci): permissions
  .github/workflows/config-reloader.yaml
  .github/workflows/fluentd-images.yaml
  .github/workflows/syslog-ng-reloader.yaml
Labels: bugfix

#1970 fix(ci): signing
  .github/workflows/config-reloader.yaml
  .github/workflows/syslog-ng-reloader.yaml
Labels: bugfix

#1971 fix(chart): correct path for clusterdomain
  charts/logging-operator/templates/_helpers.tpl
Labels: bugfix

#1991 fix(ci-e2e): make sure e2e tests are not cached
  Makefile
Labels: bug

#1988 chart: add udp_transport_type for gelf output plugin
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/outputs/gelf.md
  images/fluentd/outputs/Gemfile
  images/fluentd/outputs/Gemfile.lock
  pkg/sdk/logging/model/output/gelf.go
Labels: dependencies

#1989 feat(chart): aggregated view clusterrole
  charts/logging-operator/README.md
  charts/logging-operator/templates/userrole.yaml
  charts/logging-operator/values.yaml
Labels: enhancement
