Repository kube-logging/logging-operator, pull requests merged in 2025-01, with the labels that each got.

#1906 fix: use fully qualified images
  pkg/sdk/extensions/extensionsconfig/config.go
  pkg/sdk/extensions/extensionsconfig/config_test.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: dependencies

#1899 feat(http): add support for new available parameters
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/outputs/http.md
  pkg/sdk/logging/model/output/http.go
  pkg/sdk/logging/model/output/http_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: enhancement

#1893 fix: add missing roles to grant the use of scc to workloads
  charts/logging-operator/templates/clusterrole.yaml
  config/rbac/role.yaml
  controllers/logging/logging_controller.go
Labels: bugfix

#1917 chore: remove enabledNamespaces field
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  docs/configuration/crds/v1beta1/clusteroutput_types.md
  docs/configuration/crds/v1beta1/syslogng_clusteroutput_types.md
  pkg/sdk/logging/api/v1beta1/clusteroutput_types.go
  pkg/sdk/logging/api/v1beta1/syslogng_clusteroutput_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
Labels: bugfix

#1919 feat(config-reloader): enable setting graceful reload webhook
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/configuration/crds/v1beta1/fluentd_types.md
  pkg/resources/fluentd/appconfigmap.go
  pkg/resources/fluentd/statefulset.go
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
Labels: enhancement

#1918 feat(chart): enable defining multiple hosttailers
  charts/logging-operator/README.md
  charts/logging-operator/templates/logging/hosttailers.yaml
  charts/logging-operator/values.yaml
Labels: enhancement

#1907 chore(images): pull in fluentd image build
  .github/workflows/artifacts.yaml
  .github/workflows/ci.yaml
  .github/workflows/dependency-images.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yaml
  Makefile
  e2e/common/helpers.go
  e2e/common/setup/loggingoperator.go
  e2e/fluentd-aggregator-detached-multiple-failures/fluentd_aggregator_detached_multiple_failures_test.go
  e2e/fluentd-aggregator-detached/fluentd_aggregator_detached_test.go
  e2e/fluentd-aggregator-namespacelabel/fluentd_aggregator_test.go
  e2e/fluentd-aggregator/fluentd_aggregator_test.go
  e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
  e2e/volumedrain/volumedrain_test.go
  hack/test.sh
  hack/values.yaml
  images/fluentd/Dockerfile
  images/fluentd/README.md
  images/fluentd/entrypoint.sh
  images/fluentd/filters/Gemfile
  images/fluentd/filters/Gemfile.lock
  images/fluentd/fluent.conf
  images/fluentd/healthy.sh
  images/fluentd/outputs/Gemfile
  images/fluentd/outputs/Gemfile.lock
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  renovate.json
Labels: dependencies

#1925 chore(deps): enable fluentd gem bumps for renovate
  renovate.json
Labels: dependencies

#1926 fix: add 'ruby-bigdecimal' to solve 'Oj is not installed, and falling…
  images/fluentd/Dockerfile
Labels: dependencies

#1920 fix(validation-reconciler): correct output and flow status report
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/configuration/crds/v1beta1/logging_types.md
  pkg/resources/model/reconciler.go
  pkg/resources/model/repository.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: bugfix

#1927 fix(ci-release): version info
  .github/workflows/artifacts.yaml
  .github/workflows/release.yaml
Labels: bugfix
