Repository kube-logging/logging-operator, pull requests merged in 2025-04, with the labels that each got.

#1995 feat: move in fluentd-drain-watch
  .github/workflows/dependency-images.yaml
  .github/workflows/e2e.yaml
  .github/workflows/fluentd-drain-watch.yaml
  Makefile
  e2e/common/helpers.go
  e2e/common/setup/loggingoperator.go
  e2e/fluentd-aggregator-detached-multiple-failures/fluentd_aggregator_detached_multiple_failures_test.go
  e2e/fluentd-aggregator-detached/fluentd_aggregator_detached_test.go
  e2e/fluentd-aggregator/fluentd_aggregator_test.go
  e2e/volumedrain/volumedrain_test.go
  hack/test.sh
  images/fluentd-drain-watch/Dockerfile
  images/fluentd-drain-watch/README.md
  images/fluentd-drain-watch/drain-watch.sh
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: enhancement

#2000 fix(logging_controller): reconcile child resources
  controllers/logging/logging_controller.go
  controllers/logging/telemetry_controller_controller.go
Labels: bug

#2003 chore: migrate to v2 golangci-lint
  .golangci.yml
  Makefile
  controllers/extensions/eventtailer_controller.go
  controllers/extensions/hosttailer_controller.go
  controllers/logging/logging_controller.go
  controllers/logging/loggingroute_controller.go
  controllers/logging/telemetry_controller_controller.go
  docs/configuration/crds/v1beta1/fluentd_types.md
  docs/configuration/plugins/filters/elasticsearch_genid.md
  docs/configuration/plugins/filters/parser.md
  main.go
  pkg/resources/configcheck/configcheck.go
  pkg/resources/eventtailer/clusterrolebinding.go
  pkg/resources/eventtailer/helpers.go
  pkg/resources/eventtailer/statefulset.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentbit/daemonset.go
  pkg/resources/fluentbit/tenants.go
  pkg/resources/fluentd/appconfigmap.go
  pkg/resources/fluentd/fluentd.go
  pkg/resources/fluentd/outputsecret.go
  pkg/resources/hosttailer/helpers.go
  pkg/resources/hosttailer/hosttailer.go
  pkg/resources/kubetool/volumebuilder.go
  pkg/resources/model/repository.go
  pkg/resources/nodeagent/configsecret.go
  pkg/resources/nodeagent/daemonset.go
  pkg/resources/nodeagent/nodeagent.go
  pkg/resources/nodeagent/service.go
  pkg/resources/syslogng/configcheck.go
  pkg/resources/syslogng/configsecret.go
  pkg/resources/syslogng/outputsecret.go
  pkg/resources/syslogng/statefulset.go
  pkg/resources/syslogng/syslogng.go
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/model/filter/elasticsearch_genid.go
  pkg/sdk/logging/model/filter/parser.go
  pkg/sdk/logging/model/output/loki.go
  pkg/sdk/logging/model/output/newrelic.go
  pkg/sdk/logging/model/output/vmware_log_intelligence.go
  pkg/sdk/logging/model/render/fluent.go
  pkg/sdk/logging/model/syslogng/output/openobserve.go
  pkg/sdk/logging/model/types/builder.go
  pkg/sdk/logging/model/types/flow.go
  pkg/sdk/logging/model/types/stringmaps.go
  pkg/webhook/podhandler/podhandler.go
Labels: enhancement

#2002 feat: set default user and group
  pkg/sdk/logging/api/v1beta1/fluentd_types.go
Labels: breaking-change

#2001 fix(chart): nodeagent deprecation notice
  charts/logging-operator/README.md
  charts/logging-operator/values.yaml
Labels: bug

#2006 Add format_key and format_name in ParseSection and SingleParseSection
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_flows.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_flows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_flows.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/configuration/plugins/filters/parser.md
  pkg/sdk/logging/model/filter/parser.go
  pkg/sdk/logging/model/filter/parser_test.go
Labels: enhancement

#2004 chore: standardize naming to "Logging operator"
  ADOPTERS.md
  CONTRIBUTING.md
  README.md
  charts/logging-operator/README.md
  charts/logging-operator/README.md.gotmpl
  charts/logging-operator/values.yaml
  docs/configuration/plugins/outputs/kafka.md
  docs/configuration/plugins/outputs/loki.md
  docs/configuration/plugins/outputs/relabel.md
  docs/scaling.md
  docs/syslogng-quickstart.md
  docs/volume-drainer.md
  main.go
  pkg/sdk/logging/model/output/kafka.go
  pkg/sdk/logging/model/output/loki.go
  pkg/sdk/logging/model/output/relabel.go
Labels: documentation

#2022 fix: change q_out_size attribute in disk_buffer parameter to qout_size in SyslogNGClusterOutput/SyslogNGOutput
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
  docs/configuration/plugins/syslogng-outputs/disk_buffer.md
  docs/configuration/plugins/syslogng/outputs/disk_buffer.md
  docs/syslogng-quickstart.md
  pkg/sdk/logging/model/syslogng/config/output_tests/loki_test.go
  pkg/sdk/logging/model/syslogng/output/disk_buffer.go
Labels: bugfix

#2018 fix: change rdkafka_options format from section to hash
  pkg/sdk/logging/model/output/kafka.go
  pkg/sdk/logging/model/output/kafka_test.go
Labels: bugfix

#2023 Add support for Loki tenant-id to SyslogNGClusterOutput/SyslogNGOutput
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
  docs/configuration/plugins/syslogng-outputs/loki.md
  pkg/sdk/logging/model/syslogng/config/output_tests/loki_test.go
  pkg/sdk/logging/model/syslogng/output/loki.go
Labels: enhancement

#2011 Adapt LoggingOperator to use namespaces_regex defined in fluent-plugi…
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusterflows.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusterflows.yaml
  config/crd/bases/logging.banzaicloud.io_clusterflows.yaml
  controllers/logging/logging_controller_match_test.go
  docs/configuration/crds/v1beta1/clusterflow_types.md
  images/fluentd/Dockerfile
  pkg/resources/model/system.go
  pkg/sdk/logging/api/v1beta1/clusterflow_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/logging/model/render/fluent_test.go
  pkg/sdk/logging/model/types/router.go
Labels: enhancement

#1957 feat(hosttailer): reduce fluent-bit log level to error
  charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_hosttailers.yaml
  charts/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml
  config/crd/bases/logging-extensions.banzaicloud.io_hosttailers.yaml
  docs/configuration/crds/extensions/v1alpha1/hosttailer_types.md
  pkg/sdk/extensions/api/v1alpha1/filetailer.go
  pkg/sdk/extensions/api/v1alpha1/hosttailer_types.go
  pkg/sdk/extensions/api/v1alpha1/systemdtailer.go
Labels: enhancement

#2027 chore: prepare release
  .github/workflows/e2e.yaml
  Makefile
  charts/logging-operator/Chart.lock
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_nodeagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngconfigs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentdconfigs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_nodeagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngconfigs.yaml
  config/crd/bases/logging.banzaicloud.io_fluentdconfigs.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_nodeagents.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngconfigs.yaml
  go.mod
  go.sum
Labels: dependencies

#2028 chore: use ghcr instead of docker for fluentbit image
  pkg/sdk/extensions/extensionsconfig/config.go
  pkg/sdk/extensions/extensionsconfig/config_test.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: dependencies
