Repository kube-logging/logging-operator, pull requests merged in 2025-05, with the labels that each got.

#2032 fix(helm): priorityClassName must be of type string
  charts/logging-operator/README.md
  charts/logging-operator/values.yaml
Labels: bugfix

#2035 feat: initial axosyslog api implementation
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_axosyslogs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_axosyslogs.yaml
  charts/logging-operator/templates/clusterrole.yaml
  config/crd/bases/logging.banzaicloud.io_axosyslogs.yaml
  config/rbac/role.yaml
  controllers/logging/axosyslog_controller.go
  docs/configuration/crds/v1beta1/_index.md
  docs/configuration/crds/v1beta1/axosyslog_types.md
  main.go
  pkg/sdk/logging/api/v1beta1/axosyslog_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
Labels: enhancement

#2038 Add ip-protocol(4/6) to syslog model
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_syslogngoutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_syslogngoutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngclusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_syslogngoutputs.yaml
  docs/configuration/plugins/syslogng-outputs/syslog.md
  pkg/sdk/logging/model/syslogng/output/syslog.go
  pkg/sdk/logging/model/syslogng/output/zz_generated.deepcopy.go
Labels: bugfix

#2039 Update latest version of fluent-plugin-elasticsearch
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/plugins/outputs/elasticsearch.md
  images/fluentd/outputs/Gemfile
  images/fluentd/outputs/Gemfile.lock
  pkg/sdk/logging/model/output/aws_elasticsearch_test.go
  pkg/sdk/logging/model/output/elasticsearch.go
  pkg/sdk/logging/model/output/elasticsearch_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: enhancement

#2040 Fix incorrect doc for default LineFormat for loki
  docs/configuration/plugins/outputs/loki.md
  pkg/sdk/logging/model/output/loki.go
Labels: documentation

#2043 feat: add parameter to disable mount of /var/log directory
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_loggings.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_fluentbitagents.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_loggings.yaml
  config/crd/bases/logging.banzaicloud.io_fluentbitagents.yaml
  config/crd/bases/logging.banzaicloud.io_loggings.yaml
  docs/configuration/crds/v1beta1/fluentbit_types.md
  pkg/resources/fluentbit/daemonset.go
  pkg/sdk/logging/api/v1beta1/fluentbit_types.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
Labels: enhancement
