Repository kube-logging/logging-operator, pull requests merged in 2025-06, with the labels that each got.

#2046 chore: unify metrics probe keys name in axosyslog
  pkg/sdk/logging/model/syslogng/config/config_test.go
  pkg/sdk/logging/model/syslogng/config/log.go
Labels: enhancement

#2047 chore: fine-tune FluentdPredictedBufferGrowth
  e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
  pkg/resources/fluentd/prometheusrules.go
Labels: enhancement

#2049 fix(hosttailer): remove unused image field
  charts/logging-operator/charts/logging-operator-crds/templates/logging-extensions.banzaicloud.io_hosttailers.yaml
  charts/logging-operator/crds/logging-extensions.banzaicloud.io_hosttailers.yaml
  config/crd/bases/logging-extensions.banzaicloud.io_hosttailers.yaml
  docs/configuration/crds/extensions/v1alpha1/hosttailer_types.md
  pkg/sdk/extensions/api/v1alpha1/hosttailer_types.go
  pkg/sdk/extensions/api/v1alpha1/zz_generated.deepcopy.go
Labels: bugfix

#2059 Add support for Logicmonitor
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/charts/logging-operator-crds/templates/logging.banzaicloud.io_outputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_clusteroutputs.yaml
  charts/logging-operator/crds/logging.banzaicloud.io_outputs.yaml
  config/crd/bases/logging.banzaicloud.io_clusteroutputs.yaml
  config/crd/bases/logging.banzaicloud.io_outputs.yaml
  docs/configuration/crds/v1beta1/output_types.md
  docs/configuration/plugins/_index.md
  docs/configuration/plugins/outputs/lm_logs.md
  images/fluentd/outputs/Gemfile
  images/fluentd/outputs/Gemfile.lock
  pkg/sdk/logging/api/v1beta1/output_types.go
  pkg/sdk/logging/api/v1beta1/zz_generated.deepcopy.go
  pkg/sdk/logging/model/output/lm_logs.go
  pkg/sdk/logging/model/output/lm_logs_test.go
  pkg/sdk/logging/model/output/zz_generated.deepcopy.go
Labels: enhancement

#2056 chore: add deprecation notice on logging spec's fluentbit field
  docs/configuration/crds/v1beta1/logging_types.md
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: documentation

#2062 bugfix: mount /var/log only if config parameter is set to false
  pkg/resources/fluentbit/daemonset.go
Labels: bugfix

#2068 fix(chart,hosttailer): remove orphaned '.spec.image' as removed in ht…
  charts/logging-operator/README.md
  charts/logging-operator/templates/logging/hosttailer.yaml
  charts/logging-operator/templates/logging/hosttailers.yaml
  charts/logging-operator/values.yaml
Labels: bugfix
