Repository kube-logging/logging-operator, pull requests merged in 2025-02, with the labels that each got.

#1929 Fine tune watch selectors for less memory usage
  controllers/logging/logging_controller_test.go
  e2e/common/setup/loggingoperator.go
  e2e/logging_metrics_monitoring/logging_metrics_monitoring_test.go
  e2e/watch-selector/watch_selector_test.go
  main.go
  pkg/resources/fluentbit/configsecret.go
  pkg/resources/fluentd/appconfigmap.go
  pkg/resources/fluentd/configsecret.go
  pkg/resources/fluentd/outputsecret.go
  pkg/resources/syslogng/configcheck.go
  pkg/resources/syslogng/configsecret.go
  pkg/resources/syslogng/outputsecret.go
Labels: enhancement

#1934 chore: bump fluentbit image
  pkg/sdk/extensions/extensionsconfig/config.go
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: dependencies

#1933 fix: deprecated k8s.gcr.io registry with old version
  pkg/sdk/logging/api/v1beta1/logging_types.go
Labels: dependencies

#1935 chore: bump dependecy images
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/api/v1beta1/syslogng_types.go
Labels: dependencies

#1937 fix: cache overwrite
  main.go
Labels: bugfix

#1947 fix missing labels in clusterrole and userrole template
  Makefile
  charts/logging-operator/templates/clusterrole.yaml
  charts/logging-operator/templates/userrole.yaml
Labels: bugfix

#1949 chore: bump node-exporter
  pkg/sdk/logging/api/v1beta1/logging_types.go
  pkg/sdk/logging/api/v1beta1/syslogng_types.go
Labels: dependencies
